### ISSUE TITLE
@import foo.css when foo.scss is also present does not include the file

### ISSUE THREAD

**Issue by ybart** [rails/sass-rails#348] opened 2015-09-17 16:58 UTC
Given a assets folder with both `foo.css` and `foo.css` present. When I import the css file from an application.sass file using :

```
@import foo.css
```

In production environment, the generated application.css file contains `@import url(foo.css)` instead of the contents of css file.

Here is a sample project reproducing the issue : 

https://github.com/ybart/sass-css-import-bug/

The relevant commit highlighting the issue is : 

https://github.com/ybart/sass-css-import-bug/commit/9b9c1f93e2628a4b4b311fe786abd135d7a8e09f

To reproduce the issue, you need to to run the following commands :

```
rake assets:precompile RAILS_ENV=production
RAILS_ENV=production rails s
```

Then access http://localhost:3000/ In the browser inspector, you can see that the browser is trying to load /toto.css whether the file contents should have be included. By observing application-xxx.css, we see an unexpected import directive.

**Comment by rafaelfranca** [comment] 2015-09-18 04:50
Which version of sass are you using? I believe it is a bug in as https://github.com/sass/sass/issues/1806 that was fixed in 3.4.18.

**Comment by ybart** [comment] 2015-09-18 05:27
Gemfile.lock indicates 3.4.18

**Comment by rafaelfranca** [comment] 2015-09-18 13:39
I'd say it is a sass bug but we need go reproduce it outside Rails first.

**Comment by bolandrm** [comment] 2015-10-03 13:31
This is a known sass issue, and it is not related to having a `.scss` file with the same name in the directory.

https://github.com/sass/sass/issues/193

**Comment by bolandrm** [comment] 2015-10-03 13:33
We might want to make the sass-rails importer support this, however.

**Comment by rafaelfranca** [comment] 2015-10-05 14:48
I don't want to have more different behaviors in our importer. In fact I'd like to not have an importer at all but it is needed since sass don't want to implement glob importing. I'm closing this one. Thanks @bolandrm for investigating.

**Closed by rafaelfranca** 2015-10-05 14:48 UTC
